version: "3.1"
services:
  gateway:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./gateway
    ports:
      - 8080:80
    depends_on:
      - api
      - analytics
  cache:
    image: redis
    restart: always
  db:
    image: bitnami/mongodb
    restart: always
    volumes:
      - data:/bitnami
    user: root
    ports:
      - 27017:27017
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/code
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/code
    secrets:
      - api_port
      - db_url
      - redis_url
    environment:
      PORT_FILE: /run/secrets/api_port
      MONGODB_URL_FILE: /run/secrets/db_url
      REDIS_URL_FILE: /run/secrets/redis_url
    depends_on:
      - db
  analytics:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./analytics
    volumes:
      - ./analytics:/code
    secrets:
      - api_port
      - db_url
    environment:
      PORT_FILE: /run/secrets/api_port
      MONGODB_URL_FILE: /run/secrets/db_url
    depends_on:
      - db
  resolver:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./resolver
    volumes:
      - ./resolver/src:/usr/share/nginx/html
secrets:
  db_url:
    file: ./secrets/db_url.txt
  api_port:
    file: ./secrets/api_port.txt
  redis_url:
    file: ./secrets/redis_url.txt

volumes:
  data:
